Dont't let mdm start twice. Use a lock file.

diff --git a/mdm/src/mdm-bin b/mdm/src/mdm-bin
--- a/mdm/src/mdm-bin
+++ b/mdm/src/mdm-bin
@@ -28,6 +28,7 @@ MDM_INCLUDE=${MDM_SCRIPTS}/mdm-common
 source $MDM_INCLUDE
 
 MY_LOG=${MDM_LOGS}/mdm.log
+MDM_LOCK_FILE=/var/lock/mdm.lock
 
 CREATE_XORG_CONF=${MDM_SCRIPTS}/create-xorg-conf
 START_SEAT=${MDM_SCRIPTS}/mdm-start-seat
@@ -36,6 +37,13 @@ function exec_start() {
 	
     log --log-file-only "Multiseat Display Manager version $MDM_VERSION"
     log --log-file-only "Today is `date`."
+
+    if [ -f "$MDM_LOCK_FILE" ]; then
+        log --log-file-only "Error: mdm is already running"
+	exit 1
+    else
+        touch $MDM_LOCK_FILE
+    fi
 
     # /var/run is re-created at every reboot
     mkdir -p ${MDM_RUN}
@@ -100,6 +108,8 @@ function exec_stop() {
 	kill `cat $i` 2> /dev/null
 	rm -f $i
     done
+
+    rm -f $MDM_LOCK_FILE
 }
 
 function exec_reconfigure() {
